name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - index.html

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: .
          target_branch: gh-pages
          token: ${{ secrets.GITHUB_TOKEN }}
          commit_message: "Deploy updated website to GitHub Pages"

      - name: Print GitHub Pages URL
        run: echo "GitHub Pages deployed at https://<your-username>.github.io/gh-deployment-workflow/"
